version: '3'

services:
  dynamodb-local:
    container_name: dynamodb-local
    hostname: dynamodb
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    volumes:
      - dynamodb_data:/home/dynamodblocal
    ports:
      - "8000:8000"
    networks:
      - localnet


volumes:
  dynamodb_data:
    driver: local

networks:
  localnet:
    driver: bridge